site_name: Superpipe
site_author: Aman Dhesi, Ben Scharfstein
site_description: LLM pipelines for structured data extraction and classification
repo_name: superpipe
repo_url: https://github.com/villagecomputing/superpipe
site_url: https://superpipe.ai

theme:
  name: material
  logo: assets/superpipe.png
  features:
    - navigation.sections
    - navigation.tracking
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.path
    - navigation.indexes
    - navigation.footer
    - search.suggest
    - search.highlight
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Introduction:
      - index.md
      - build.md
      - evaluate.md
      - optimize.md
      - why.md
      - use_cases.md
      - workflow.md
      - principles.md
      - roadmap.md
  - Concepts:
      - concepts/index.md
      - Steps:
          - concepts/steps/index.md
          - concepts/steps/LLMStep.md
          - concepts/steps/LLMStructuredStep.md
          - concepts/steps/SERPStep.md
          - concepts/steps/EmbeddingSearchStep.md
          - concepts/steps/CustomStep.md
      - Pipelines: concepts/pipelines.md
      - Models: concepts/models.md
      - Grid Search: concepts/grid_search.md
  - Examples:
      - examples/index.md
      - examples/web_scraping/web_scraping.ipynb
      - examples/product_categorization/product_categorization.ipynb
      - examples/business_classification/business_classification.ipynb
      - examples/comparing_pipelines/furniture.ipynb
      - examples/custom_eval/jokes.ipynb

  - Superpipe Studio:
      - studio/index.md

  - Blog:
      - blog/index.md

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: villagecomputing
      repo: superpipe
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - toc:
      permalink: true

plugins:
  - mkdocs-jupyter:
      include_source: True
  - search
  - social:
      cards_layout: default
  - blog

social:
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/villagecompute
  - icon: fontawesome/brands/github
    link: https://github.com/villagecomputing

extra:
  analytics:
    provider: google
    property: G-004PC5QJ4H
