site_name: Superpipe

theme:
  name: material
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.tabs
    - navigation.tracking
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.path
    - navigation.indexes
    - navigation.footer

nav:
  - Introduction:
      - index.md
      - getting_started.md
      - why_superpipe.md
  - Using Superpipe:
      - using/index.md
      - Pipelines: using/pipelines.md
      - Models: using/models.md
      - Grid Search: using/grid_search.md
      - Steps:
          - using/steps/index.md
          - using/steps/LLMNormalStep.md
          - using/steps/LLMStructuredStep.md
          - using/steps/SERPStep.md
          - using/steps/EmbeddingClassificationStep.md
          - using/steps/CustomStep.md

  - Use Cases:
      - use_cases/index.md
      - Use Case 1: use_cases/index.md
  - Examples:
      - examples/index.md
      - Example 1: examples/index.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
